
import java.awt.event.KeyEvent;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nuwan
 */
public class billings extends javax.swing.JFrame {
    
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    /**
     * Creates new form billings
     */
    public billings() {
        initComponents();
        con = (Connection) databaseconnection.connection();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        DefaultTableModel model = new DefaultTableModel();
        itemsub.setEditable(false);
        vsub.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billitemtable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bitde = new javax.swing.JTextField();
        bqty = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bitid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bpr = new javax.swing.JTextField();
        itemsub = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mtpay = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        vsub = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        vmtable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        vmprice = new javax.swing.JTextField();
        reg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        barcode = new javax.swing.JTextField();
        salespay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Billing");

        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home btn.png"))); // NOI18N
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homebtn)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        billitemtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Description", "Price", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(billitemtable);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bitde.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        bqty.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Qty");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Item Description");

        bitid.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        bitid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitidActionPerformed(evt);
            }
        });
        bitid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bitidKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Item ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Price");

        bpr.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        itemsub.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itemsub.setText("0");
        itemsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsubActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Sub Total");

        mtpay.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mtpay.setText("Pay");
        mtpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtpayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mtpay, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(itemsub, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bqty, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                            .addComponent(bitid))
                                        .addGap(73, 73, 73)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bitde, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(105, 105, 105)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bpr, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))))
                .addGap(135, 135, 135))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bitid)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bitde)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemsub)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(mtpay)
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("                 Sales               ", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        vsub.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        vsub.setText("0");
        vsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsubActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("Sub Total");

        vmtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle ID", "Register Number", "Maintenance", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(vmtable);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        vmprice.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        reg.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Register Number");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("Price");

        des.setColumns(20);
        des.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        des.setRows(5);
        jScrollPane2.setViewportView(des);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("Maintenance Details");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Vehicle_ID");

        barcode.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });
        barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barcodeKeyPressed(evt);
            }
        });

        salespay.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        salespay.setText("Pay");
        salespay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salespayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(vsub, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(salespay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(55, 55, 55)
                                .addComponent(vmprice, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(barcode)))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(reg, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vsub)
                            .addComponent(jLabel12))
                        .addGap(38, 38, 38)
                        .addComponent(salespay))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(vmprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("          Maintenance          ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void qcheck()
    {
    String name = bitid.getText();
    
    try
    
    {
            java.sql.PreparedStatement preparedStmt = con.prepareStatement("select * from inventoryitems where Item_ID=?");
            preparedStmt.setString(1, name);
            rs = preparedStmt.executeQuery();
    
            while(rs.next())
            {
            int currentqty;
            
            currentqty =rs.getInt("Available_Quantity");
            
            int price = Integer.parseInt(bpr.getText());
            int qty = Integer.parseInt(bqty.getText());
            
            int tot= price*qty;
            
            if (qty >= currentqty)
            {
            JOptionPane.showMessageDialog(this,"Not enough items in the inventory"+"\n"+ "Available quantity is "+currentqty);
            }
            else{
                DefaultTableModel model = (DefaultTableModel)billitemtable.getModel();
                model.addRow(new Object[]
                {
                    bitid.getText(),
                    bitde.getText(),
                    bpr.getText(),
                    bqty.getText(),
                    tot 
                });
                
                   int sum=0;
                     for(int i=0; i<billitemtable.getRowCount(); i++)
                     {
                     sum = sum + Integer.parseInt(billitemtable.getValueAt(i,4).toString());
                     
                     itemsub.setText(Integer.toString(sum)); 
                
                     }
        
                    bitid.setText("");
                    bitde.setText("");
                    bpr.setText("");
                    bqty.setText("");
                    bitid.requestFocus();
                }
            
           
            }
                  
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    
    }
    
    
    
    
    
    private void vmsalesadd()
    {
    
     try
    
    {
    
                DefaultTableModel model = (DefaultTableModel)vmtable.getModel();
                model.addRow(new Object[]
                {
                    barcode.getText(),
                    reg.getText(),
                    des.getText(),
                    vmprice.getText(),
                    
                });
                
                    int sum=0;
                     for(int i=0; i<vmtable.getRowCount(); i++)
                     {
                     sum = sum + Integer.parseInt(vmtable.getValueAt(i,3).toString());
                     
                     vsub.setText(Integer.toString(sum));
                   
                    barcode.setText("");
                    reg.setText("");
                    vmprice.setText("");
                    des.setText("");
                    barcode.requestFocus();
                }
                  
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    
    
    
    }
    
    
    
    
    private void itemsales()
    {
        
        try {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDateTime now =LocalDateTime.now();
            String date =dtf.format(now);
            
            String sub = itemsub.getText();
            int lastinsertid= 0;
            
            java.sql.PreparedStatement preparedStmt= con.prepareStatement("insert into itemsalesfinal(date, issubt)values(?,?)", Statement.RETURN_GENERATED_KEYS);
            preparedStmt.setString(1, date);
            preparedStmt.setString(2, sub);
            preparedStmt.executeUpdate();
            ResultSet generatedKeyResult = preparedStmt.getGeneratedKeys();
            
            if(generatedKeyResult.next())
            {
                lastinsertid = generatedKeyResult.getInt(1);
            
            }
            if (sub.equals("0")){
            JOptionPane.showMessageDialog(this, "Please add items to cart");
            }
            else{
            JOptionPane.showMessageDialog(this,"Paid" + "\nBill id "+lastinsertid);
            itemsub.setText("0");
            }
            
            
            int rows = billitemtable.getRowCount();
            
            String query ="insert into itemsales(date, sales_id, item_id, price, qty, total)values(?,?,?,?,?,?)";
            java.sql.PreparedStatement pstmt= con.prepareStatement(query);
            
            String itemid="";
            int price=0;
            int qty=0;
            int total=0;
            
            for(int i=0; i<billitemtable.getRowCount(); i++)
            {
             itemid = (String)billitemtable.getValueAt(i,0);
             price = Integer.parseInt((String) billitemtable.getValueAt(i,2).toString());
             qty = Integer.parseInt((String) billitemtable.getValueAt(i,3).toString());
             total = Integer.parseInt((String) billitemtable.getValueAt(i,4).toString());
             
             pstmt.setString(1,date);
             pstmt.setInt(2,lastinsertid);
             pstmt.setString(3,itemid);
             pstmt.setInt(4,price);
             pstmt.setInt(5,qty);
             pstmt.setInt(6,total);
             pstmt.executeUpdate();
             
            }
        
            String query1 ="update inventoryitems set Available_Quantity= Available_Quantity-? where Item_ID=?";
            java.sql.PreparedStatement prstmt= con.prepareStatement(query1);
            
            for(int i=0; i<billitemtable.getRowCount(); i++)
            {
             itemid = (String)billitemtable.getValueAt(i,0);
             
             qty = Integer.parseInt((String) billitemtable.getValueAt(i,3).toString());
             
             
             prstmt.setInt(1,qty);
             prstmt.setString(2,itemid);
             prstmt.execute();
             
            }
           
        pstmt.addBatch();
       
        }
         catch(Exception e)
    {
        System.out.println(e);
    
    
    
    }
    }
    
  
    
    
    
    private void vmsales()
    {
    try {
        
    
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDateTime now =LocalDateTime.now();
            String date =dtf.format(now);
            
            String sub = vsub.getText();
            int lastinsertid= 0;
    
            java.sql.PreparedStatement preparedStmt= con.prepareStatement("insert into vmfinal(date, vmsubt)values(?,?)", Statement.RETURN_GENERATED_KEYS);
            preparedStmt.setString(1, date);
            preparedStmt.setString(2, sub);
            preparedStmt.executeUpdate();
            ResultSet generatedKeyResult = preparedStmt.getGeneratedKeys();
            
            if(generatedKeyResult.next())
            {
                lastinsertid = generatedKeyResult.getInt(1);
            
            }
            if (sub.equals("0")){
            JOptionPane.showMessageDialog(this, "Please add maintenance details");
            }
            else{
            JOptionPane.showMessageDialog(this, "Paid"+ "\nBill id "+ lastinsertid);
            vsub.setText("0");
            }
            
            int rows = vmtable.getRowCount();
    
            String query ="insert into vmsales(vmsales_id, Vehicle_Id, date, maintenance, vmtotal)values(?,?,?,?,?)";
            java.sql.PreparedStatement pstmt= con.prepareStatement(query);
            
            String Vehicle_ID="";
            String vreg="";
            String maintenance="";
            int vmtotal=0;
    
            for(int i=0; i<vmtable.getRowCount(); i++)
            {
             Vehicle_ID = (String)vmtable.getValueAt(i,0);
             maintenance = (String)vmtable.getValueAt(i,2);
             vmtotal = Integer.parseInt((String) vmtable.getValueAt(i,3).toString());
             
             pstmt.setInt(1,lastinsertid);
             pstmt.setString(2,Vehicle_ID);
             pstmt.setString(3,date);
             pstmt.setString(4,maintenance);
             pstmt.setInt(5,vmtotal);
             pstmt.executeUpdate();
             
            }
    
    
    pstmt.addBatch();
    
    }
    
            catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel)billitemtable.getModel();
        model.removeRow(billitemtable.getSelectedRow());

        int sum=0;
        for(int i=0; i<billitemtable.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(billitemtable.getValueAt(i,4).toString());

            itemsub.setText(Integer.toString(sum));

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        qcheck();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bitidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bitidActionPerformed

    private void bitidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bitidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            String name = bitid.getText();
            try
            {

                java.sql.PreparedStatement preparedStmt = con.prepareStatement("select * from inventoryitems where Item_ID=?");
                preparedStmt.setString(1, name);
                rs = preparedStmt.executeQuery();

                if (rs.next()== false)
                {
                    JOptionPane.showMessageDialog(this, "Item not found");

                }
                else{
                    String itemdes = rs.getString("Item_Description");
                    String itempri = rs.getString("Price");

                    bitde.setText(itemdes);
                    bpr.setText(itempri);

                }

            }
            catch(Exception e)
            {
                System.out.println(e);
            }

        }

    }//GEN-LAST:event_bitidKeyPressed

    private void itemsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemsubActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        vmsalesadd();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeActionPerformed

    private void barcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcodeKeyPressed

        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            try {

                java.sql.PreparedStatement preparedStmt = con.prepareStatement("select * from vehicles where Vehicle_ID='"+barcode.getText()+"'");

                Statement s =con.createStatement();
                rs = preparedStmt.executeQuery();
                if (rs.next()== false)
                {
                    JOptionPane.showMessageDialog(this, "Incorrect Vehicle_ID");

                }
                else{
                    String itemname = rs.getString("Register_Number");

                    reg.setText(itemname);

                }
            } catch (Exception e)
            {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_barcodeKeyPressed

    private void salespayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salespayActionPerformed
        // TODO add your handling code here:
        vmsales();
        DefaultTableModel model = (DefaultTableModel)vmtable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_salespayActionPerformed

    private void mtpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtpayActionPerformed
        // TODO add your handling code here:
        itemsales();
        DefaultTableModel model = (DefaultTableModel)billitemtable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_mtpayActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home view = new home();
        view.setVisible(true);
    }//GEN-LAST:event_homebtnActionPerformed

    
    
    private void vsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vsubActionPerformed

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown

    }//GEN-LAST:event_jPanel3ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billings().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcode;
    private javax.swing.JTable billitemtable;
    private javax.swing.JTextField bitde;
    private javax.swing.JTextField bitid;
    private javax.swing.JTextField bpr;
    private javax.swing.JTextField bqty;
    private javax.swing.JTextArea des;
    private javax.swing.JButton homebtn;
    private javax.swing.JTextField itemsub;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton mtpay;
    private javax.swing.JTextField reg;
    private javax.swing.JButton salespay;
    private javax.swing.JTextField vmprice;
    private javax.swing.JTable vmtable;
    private javax.swing.JTextField vsub;
    // End of variables declaration//GEN-END:variables
}
