
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nuwan
 */
public class reports extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    
    /**
     * 
     * Creates new form reports
     */
    public reports() {
        initComponents();
        con = (Connection) databaseconnection.connection();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        salesdailydate = new com.toedter.calendar.JDateChooser();
        salestodate = new com.toedter.calendar.JDateChooser();
        salesfromdate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        maindailydate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        mainfromdate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        maintodate = new com.toedter.calendar.JDateChooser();
        salesgroup = new javax.swing.JButton();
        salesdaily = new javax.swing.JButton();
        maindaily = new javax.swing.JButton();
        maingroup = new javax.swing.JButton();
        backbtn_V = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Maintenance Reports");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Sales Reports");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Daily report");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("To");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("From");

        salesdailydate.setDateFormatString("yyyy-MM-dd\n");
        salesdailydate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        salestodate.setDateFormatString("yyyy-MM-dd\n");
        salestodate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        salesfromdate.setDateFormatString("yyyy-MM-dd\n");
        salesfromdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Daily report");

        maindailydate.setDateFormatString("yyyy-MM-dd\n");
        maindailydate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("From");

        mainfromdate.setDateFormatString("yyyy-MM-dd\n");
        mainfromdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("To");

        maintodate.setDateFormatString("yyyy-MM-dd\n");
        maintodate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        salesgroup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salesgroup.setText("Generate report");
        salesgroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesgroupActionPerformed(evt);
            }
        });

        salesdaily.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salesdaily.setText("Generate report");
        salesdaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesdailyActionPerformed(evt);
            }
        });

        maindaily.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maindaily.setText("Generate report");
        maindaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maindailyActionPerformed(evt);
            }
        });

        maingroup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maingroup.setText("Generate report");
        maingroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maingroupActionPerformed(evt);
            }
        });

        backbtn_V.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back btn.png"))); // NOI18N
        backbtn_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn_VActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(salesdailydate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(maindailydate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(162, 162, 162))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(salesfromdate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(salestodate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mainfromdate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maintodate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maingroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maindaily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salesgroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salesdaily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(backbtn_V, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(backbtn_V))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(salesdailydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salesdaily))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(salesgroup, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salesfromdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salestodate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maindailydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(maindaily))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(maintodate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainfromdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maingroup, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(129, 129, 129))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salesgroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesgroupActionPerformed
        // TODO add your handling code here:
        
        try{
        
         
        
           String date1 =((JTextField)salesfromdate.getDateEditor().getUiComponent()).getText();
           String date2 =((JTextField)salestodate.getDateEditor().getUiComponent()).getText();

    
        JasperDesign jdesign = JRXmlLoader.load("C:\\Inventory_and_sales_mgt_system\\src\\Reports\\report1.jrxml");
        
        String query = "select * from itemsales where date>='"+date1.trim()+"'AND date<='"+date2.trim()+"' ";
        
        java.sql.PreparedStatement preparedStmt = con.prepareStatement(query);
               
        JRDesignQuery updateQuery = new JRDesignQuery();
        updateQuery.setText(query);
        
        jdesign.setQuery(updateQuery);
        
        JasperReport jreport = JasperCompileManager.compileReport(jdesign);
        JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
        
        JasperViewer.viewReport(jprint,false);
        salesfromdate.setDate(null);
        salestodate.setDate(null);

        }
        catch(Exception e)
        {
        System.out.println(e);
        }
    }//GEN-LAST:event_salesgroupActionPerformed

    private void salesdailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesdailyActionPerformed
        // TODO add your handling code here:
        
        try{
        
         
        
           String date1 =((JTextField)salesdailydate.getDateEditor().getUiComponent()).getText();
           
    
        JasperDesign jdesign = JRXmlLoader.load("C:\\Inventory_and_sales_mgt_system\\src\\Reports\\report1.jrxml");
        
        String query = "select * from itemsales where date='"+date1.trim()+"'";
        
        java.sql.PreparedStatement preparedStmt = con.prepareStatement(query);
               
        JRDesignQuery updateQuery = new JRDesignQuery();
        updateQuery.setText(query);
        
        jdesign.setQuery(updateQuery);
        
        JasperReport jreport = JasperCompileManager.compileReport(jdesign);
        JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
        
        JasperViewer.viewReport(jprint,false);
        salesdailydate.setDate(null);

        }
        catch(Exception e)
        {
        System.out.println(e);
        }
          
    }//GEN-LAST:event_salesdailyActionPerformed

    private void maindailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maindailyActionPerformed
        // TODO add your handling code here:
        
        try{
        
         
        
           String date1 =((JTextField)maindailydate.getDateEditor().getUiComponent()).getText();
           
    
        JasperDesign jdesign = JRXmlLoader.load("C:\\Inventory_and_sales_mgt_system\\src\\Reports\\report2.jrxml");
        
        String query = "select * from vmsales where date='"+date1.trim()+"'";
        
        java.sql.PreparedStatement preparedStmt = con.prepareStatement(query);
              
        JRDesignQuery updateQuery = new JRDesignQuery();
        updateQuery.setText(query);
        
        jdesign.setQuery(updateQuery);
        
        JasperReport jreport = JasperCompileManager.compileReport(jdesign);
        JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
        
        JasperViewer.viewReport(jprint,false);
        maindailydate.setDate(null);

        }
        catch(Exception e)
        {
        System.out.println(e);
        }
    
    }//GEN-LAST:event_maindailyActionPerformed

    private void maingroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maingroupActionPerformed
        // TODO add your handling code here:
        
         try{
        
         
        
           String date1 =((JTextField)mainfromdate.getDateEditor().getUiComponent()).getText();
           String date2 =((JTextField)maintodate.getDateEditor().getUiComponent()).getText();
    
        JasperDesign jdesign = JRXmlLoader.load("C:\\Inventory_and_sales_mgt_system\\src\\Reports\\report2.jrxml");
        
        String query = "select * from vmsales where date>='"+date1.trim()+"'AND date<='"+date2.trim()+"' ";
        
        java.sql.PreparedStatement preparedStmt = con.prepareStatement(query);
               
        JRDesignQuery updateQuery = new JRDesignQuery();
        updateQuery.setText(query);
        
        jdesign.setQuery(updateQuery);
        
        JasperReport jreport = JasperCompileManager.compileReport(jdesign);
        JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
        
        JasperViewer.viewReport(jprint,false);
        mainfromdate.setDate(null);
        maintodate.setDate(null);

        }
        catch(Exception e)
        {
        System.out.println(e);
        }
    }//GEN-LAST:event_maingroupActionPerformed

    private void backbtn_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn_VActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home view = new home();
        view.setVisible(true);
    }//GEN-LAST:event_backbtn_VActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn_V;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton maindaily;
    private com.toedter.calendar.JDateChooser maindailydate;
    private com.toedter.calendar.JDateChooser mainfromdate;
    private javax.swing.JButton maingroup;
    private com.toedter.calendar.JDateChooser maintodate;
    private javax.swing.JButton salesdaily;
    private com.toedter.calendar.JDateChooser salesdailydate;
    private com.toedter.calendar.JDateChooser salesfromdate;
    private javax.swing.JButton salesgroup;
    private com.toedter.calendar.JDateChooser salestodate;
    // End of variables declaration//GEN-END:variables
}
